export type UserTags = string[];

export const TAGS = [
	'sat prep',
	'act prep',
	'calculus',
	'algebra',
	'geometry',
	'physics',
	'chemistry',
	'biology',
	'computer science',
	'python',
	'java',
	'c++',
	'web development',
	'data science',
	'machine learning',
	'economics',
	'statistics',
	'psychology',
	'history',
	'english literature',
	'essay writing',
	'resume review',
	'interview prep',
	'college applications',
	'scholarship advice',
	'study skills',
	'time management',
	'career coaching',
	'public speaking',
	'foreign languages',
	'art & design',
	'music theory',
	'microeconomics',
	'macroeconomics',
	'organic chemistry',
	'astronomy',
	'sociology',
	'philosophy',
	'political science',
	'anthropology',
	'linguistics',
	'marketing',
	'finance',
	'accounting',
	'business strategy',
	'entrepreneurship',
	'digital marketing',
	'ux/ui design',
	'graphic design',
	'video editing',
	'photography',
	'creative writing',
	'journalism',
	'environmental science',
	'geology',
	'neuroscience',
	'anatomy',
	'physiology',
	'kinesiology',
	'nursing',
	'public health',
	'pre-med advice',
	'pre-law advice',
	'lsat prep',
	'gmat prep',
	'gre prep',
	'mcat prep',
	'soft skills',
	'leadership',
	'project management'
];
