export type UserTags = string[];

export const UNIVERSITIES = [
	'Harvard University',
	'Stanford University',
	'Massachusetts Institute of Technology (MIT)',
	'Princeton University',
	'Yale University',
	'Columbia University',
	'University of California, Berkeley',
	'University of Oxford',
	'University of Cambridge',
	'California Institute of Technology (Caltech)',
	'University of Chicago',
	'Imperial College London',
	'ETH Zurich',
	'University College London (UCL)',
	'National University of Singapore (NUS)',
	'University of Pennsylvania',
	'Tsinghua University',
	'Peking University',
	'Cornell University',
	'University of Toronto',
	'University of Edinburgh',
	'Nanyang Technological University (NTU)',
	'University of Hong Kong (HKU)',
	'The University of Tokyo',
	'University of Melbourne',
	'University of New South Wales (UNSW Sydney)',
	'University of British Columbia',
	'McGill University',
	'Australian National University',
	'University of Sydney',
	'University of Queensland',
	'Monash University',
	'Seoul National University',
	'Kyoto University',
	'Technical University of Munich',
	'Heidelberg University',
	'Delft University of Technology',
	'University of Amsterdam',
	'KU Leuven',
	'Sorbonne University',
	'Ecole Polytechnique Federale de Lausanne (EPFL)',
	"King's College London",
	'London School of Economics (LSE)',
	'Duke University',
	'Johns Hopkins University',
	'Northwestern University',
	'University of California, Los Angeles (UCLA)',
	'New York University (NYU)',
	'University of Michigan-Ann Arbor',
	'University of Washington',
	'Carnegie Mellon University',
	'University of California, San Diego (UCSD)',
	'Georgia Institute of Technology',
	'University of Texas at Austin',
	'Lomonosov Moscow State University',
	'Moscow Institute of Physics and Technology (MIPT)',
	'Bauman Moscow State Technical University',
	'HSE University',
	'Saint Petersburg State University'
];

export const TAGS = [
	'sat prep',
	'act prep',
	'calculus',
	'algebra',
	'geometry',
	'physics',
	'chemistry',
	'biology',
	'computer science',
	'python',
	'java',
	'c++',
	'web development',
	'data science',
	'machine learning',
	'economics',
	'statistics',
	'psychology',
	'history',
	'english literature',
	'essay writing',
	'resume review',
	'interview prep',
	'college applications',
	'scholarship advice',
	'study skills',
	'time management',
	'career coaching',
	'public speaking',
	'foreign languages',
	'art & design',
	'music theory',
	'microeconomics',
	'macroeconomics',
	'organic chemistry',
	'astronomy',
	'sociology',
	'philosophy',
	'political science',
	'anthropology',
	'linguistics',
	'marketing',
	'finance',
	'accounting',
	'business strategy',
	'entrepreneurship',
	'digital marketing',
	'ux/ui design',
	'graphic design',
	'video editing',
	'photography',
	'creative writing',
	'journalism',
	'environmental science',
	'geology',
	'neuroscience',
	'anatomy',
	'physiology',
	'kinesiology',
	'nursing',
	'public health',
	'pre-med advice',
	'pre-law advice',
	'lsat prep',
	'gmat prep',
	'gre prep',
	'mcat prep',
	'soft skills',
	'leadership',
	'project management'
];

export interface MentorFilters {
	q?: string;
	university?: string;
	tags?: string[];
	minPrice?: number;
	maxPrice?: number;
	sort?: string;
}

export type SortOption = {
	label: string;
	value: string;
};

export const SORT_OPTIONS: SortOption[] = [
	{ label: 'Newest', value: '-created' },
	{ label: 'Price: Low to High', value: 'hourRateCents' },
	{ label: 'Price: High to Low', value: '-hourRateCents' }
];
